import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import AOSInit from "@/utils/aos";

export const metadata = {
  title: "رستوران پوکو",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AOSInit />
        {children}
      </body>
    </html>
  );
}
